name: Must run on custom runner

on: push

jobs:
  set-vars-from-file:
    runs-on: self-hosted
    name: import
    steps:
#       - name: import
#         uses: tw3lveparsecs/github-actions-setvars@v0.1
#         with:
#           envFilePath: ./vars.env

      - name: output
        run: |
          pwd
          ls -la
          cd ..
          pwd
          ls -la
          echo 'hello, world'
          echo $HOSTNAME
