name: Must run on custom runner

on: push

jobs:
  set-vars-from-file:
    runs-on: self-hosted
    name: import
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: TheObtuseAutodidact/github-actions
          
      - name: import
        uses: tw3lveparsecs/github-actions-setvars@v0.1
        with:
          envFilePath: _work/github-actions/github-actions/vars.env

      - name: output
        run: |
          pwd
          echo 'hello, world'
          echo $HOSTNAME
          echo 'FOO = ${{env.FOO}}'
          echo 'BAR = ${{env.BAR}}'
          echo 'BAZ = ${{env.BAZ}}'
