name: Must run on custom runner

on: push

jobs:
  set-vars-from-file:
    runs-on: self-hosted
    name: import
    steps:
      - name: import
        uses: tw3lveparsecs/github-actions-setvars@v0.1
        with:
          envFilePath: /home/cloud_user/vars.env

      - name: output
        run: |
          pwd
          echo 'hello, world'
          echo $HOSTNAME
          echo 'FOO = ${FOO}'
          echo 'BAR = ${BAR}'
          echo 'BAZ = ${BAZ}'
